### ISSUE TITLE
--allow-root

### ISSUE THREAD

**Issue by tinof** [humanmade/Cavalcade#102]
I followed this guide: https://guides.wp-bullet.com/configure-cavalcade-for-scaling-wordpress-wp-cron-to-100-jobs/

And I ran into the following problem:

> [1176] Worker ret: 1
> [1177] Worker status: Array
> (
>     [command] => wp cavalcade run 1177
>     [pid] => 4392
>     [running] =>
>     [signaled] =>
>     [stopped] =>
>     [exitcode] => 1
>     [termsig] => 0
>     [stopsig] => 0
> )
> 
> [1177] Worker shutting down...
> [1177] Worker out:
> [1177] Worker err: Error: YIKES! It looks like you're running this as root. You probably meant to run this as the user that your WordPress installation exists under.
> 
> If you REALLY mean to run this as root, we won't stop you, but just bear in mind that any code on this site will then have full control of your server, making it quite DANGEROUS.
> 
> If you'd like to continue as root, please run this again, adding this flag:  --allow-root
> 
> If you'd like to run it as the user that this site is under, you can run the following to become the respective user:
> 
>     sudo -u USER -i -- wp <command>

So if I get this right,  wp cavalcade run 1177 should be with "--allow-root". Where exactly should I add the "--allow-root" part?

Using Centminmod with Centos.

Thanks for your work on this!

**Comment by markhughes** [comment]
You'll want whatever is starting the runner to start it like that.

https://github.com/humanmade/Cavalcade-Runner/blob/master/systemd.service#L11

But you really shouldn't run it as root, that's super dangerous!

**Comment by rmccue** [comment]
This is happening because you're running Cavalcade Runner as root, but we don't recommend that. You should instead run it as the correct user with access to WordPress, which in many cases is `www-data`.

The example systemd config file [includes this configuration for you](https://github.com/humanmade/Cavalcade-Runner/blob/3ab6824b7afcff70210c6d74d7c85dcc28ecd00a/systemd.service#L10), so you should just update that as needed if your user differs.

Avoid `--allow-root`, because it will give any code in WordPress (such as plugins or themes) access to do *anything* on your system, including executing arbitrary system-level code.

**Comment by roborourke** [comment]
Closing out as no further action required.
