### ISSUE TITLE
Ready for a go?

### ISSUE THREAD

**Issue by alexphelps** [humanmade/Cavalcade#5]
@rmccue Cavalcade looks great and attacks a real problem with wp-cron and larger multisites. Is this ready to give a try with the expectations of a few minor issues but nothing crazy?

I'd be happy to give our feedback on trying to use this you need some beta testers to help the project.

**Comment by rmccue** [comment]
I was actually thinking about this the other day; I think I'm ready to call this stable. :)

We're running it in production across installs with tens of thousands of sites on multisite, and hundreds of thousands of jobs. The daemon is also installed across our entire server infrastructure, running in the background, so that part is definitely stable.

Give it a shot, let me know how it goes, and we'll see if we can work out any issues :)

**Comment by alexphelps** [comment]
@rmccue OK, we'll give it a go and let you know if we run into any issues. We're going to test it on a multisite ~1000 active sites.
